# Generated by Django 4.2 on 2023-09-15 08:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meeting", "0004_alter_meeting_options_alter_presentation_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="joint",
            field=ckeditor.fields.RichTextField(
                blank=True, help_text="共催を入力してください.", null=True, verbose_name="共催"
            ),
        ),
    ]
