# Generated by Django 4.2 on 2023-09-19 07:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meeting", "0005_alter_meeting_joint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="style",
            field=models.IntegerField(
                default="0",
                help_text="0:通常スタイル時間有，1:通常スタイル時間無, 2:表彰有, 3:pdfスタイル",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
                verbose_name="表示スタイル",
            ),
        ),
    ]
