# Generated by Django 4.1 on 2023-09-23 07:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meeting", "0006_alter_meeting_style"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presentation",
            name="authors",
            field=ckeditor.fields.RichTextField(
                blank=True,
                help_text="例) 〇山田太郎（〇〇大学），山田二郎（〇〇大学），発表者の前に〇をつける",
                null=True,
                verbose_name="講演者と所属",
            ),
        ),
    ]
