# Generated by Django 4.1 on 2023-10-09 06:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meeting", "0007_alter_presentation_authors"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meeting",
            options={"verbose_name": "meeting_name", "verbose_name_plural": "研究会テーブル"},
        ),
        migrations.AlterModelTable(
            name="meeting",
            table="meeting_list",
        ),
    ]
