# Generated by Django 4.1 on 2023-10-09 08:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meeting", "0008_alter_meeting_options_alter_meeting_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="style",
            field=models.IntegerField(
                default="0",
                help_text="0:通常スタイル時間有, 1:表彰有, 2:pdfスタイル",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ],
                verbose_name="表示スタイル",
            ),
        ),
    ]
