# Generated by Django 4.1 on 2023-10-11 10:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meeting", "0011_presentation_prize"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presentation",
            name="authors",
            field=ckeditor.fields.RichTextField(
                blank=True,
                help_text="例) 〇山田 太郎（〇〇大学），山田 二郎（〇〇大学），発表者の前に〇をつける",
                null=True,
                verbose_name="講演者と所属",
            ),
        ),
    ]
