# Generated by Django 4.1 on 2023-10-12 14:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meeting", "0012_alter_presentation_authors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presentation",
            name="authors",
            field=ckeditor.fields.RichTextField(
                blank=True,
                default="〇山田 太郎（〇〇大学）",
                help_text="例) 〇山田 太郎（〇〇大学），山田 二郎（〇〇大学），発表者の前に〇をつける",
                null=True,
                verbose_name="講演者と所属",
            ),
        ),
        migrations.AlterField(
            model_name="presentation",
            name="time",
            field=models.CharField(
                blank=True,
                default="13:00-15:00",
                help_text="講演者の講演時間を入力してください．例：13:10-13:45",
                max_length=50,
                null=True,
                verbose_name="時間",
            ),
        ),
    ]
