# Generated by Django 4.2.2 on 2023-10-27 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("meeting", "0013_alter_presentation_authors_alter_presentation_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="カテゴリ名")),
            ],
            options={
                "verbose_name": "meetingcategory_name",
                "verbose_name_plural": "meetingcategory",
                "db_table": "meetingcategory_list",
            },
        ),
        migrations.AddField(
            model_name="meeting",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="meetingcategory",
                related_query_name="fmeetingcategory",
                to="meeting.meetingcategory",
                verbose_name="カテゴリ",
            ),
        ),
    ]
