# Generated by Django 4.2.2 on 2023-10-27 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("meeting", "0016_alter_meeting_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="application",
            field=models.ForeignKey(
                blank=True,
                help_text="研究会参加の申込方法を入力してください．",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="meetingapplication",
                related_query_name="fmeetingapplication",
                to="meeting.footer",
                verbose_name="研究会参加申込",
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="entrancefee",
            field=models.ForeignKey(
                blank=True,
                help_text="参加費を入力してください．",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="meetingentrancefee",
                related_query_name="fmeetingentrancefee",
                to="meeting.footer",
                verbose_name="参加費",
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="inquiry",
            field=models.ForeignKey(
                blank=True,
                help_text="問合せ先を入力してください．",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="meetinginquiry",
                related_query_name="fmeetinginquiry",
                to="meeting.footer",
                verbose_name="問合せ先",
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="key",
            field=models.CharField(
                help_text="「西暦_回数」を入力してください.例：2022_2 (研究会以外の場合は「西暦_カテゴリ名」)",
                max_length=20,
                verbose_name="研究会のキー",
            ),
        ),
    ]
