# Generated by Django 4.2.2 on 2023-10-27 02:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "meeting",
            "0017_alter_meeting_application_alter_meeting_entrancefee_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="location",
            field=ckeditor.fields.RichTextField(
                blank=True, help_text="開催する場所を入力してください．", null=True, verbose_name="場所"
            ),
        ),
    ]
