# Generated by Django 4.2.2 on 2023-10-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meeting", "0018_alter_meeting_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meeting",
            name="file",
        ),
        migrations.AddField(
            model_name="presentation",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="meeting/", verbose_name="pdfファイル"
            ),
        ),
    ]
