# Generated by Django 4.2.2 on 2023-10-27 06:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meeting", "0019_remove_meeting_file_presentation_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presentation",
            name="title",
            field=ckeditor.fields.RichTextField(
                blank=True,
                help_text="講演のタイトルを入力してください．",
                null=True,
                verbose_name="タイトル",
            ),
        ),
    ]
