# Generated by Django 4.2.2 on 2024-01-11 02:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meeting", "0020_alter_presentation_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footer",
            name="body",
            field=ckeditor.fields.RichTextField(
                help_text="本文を入力してください．(段落の書式は「標準」が推奨)", verbose_name="本文"
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="joint",
            field=ckeditor.fields.RichTextField(
                blank=True,
                help_text="共催を入力してください.(段落の書式は「標準」が推奨)",
                null=True,
                verbose_name="共催",
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="location",
            field=ckeditor.fields.RichTextField(
                blank=True,
                help_text="開催する場所を入力してください．(段落の書式は「標準」が推奨)",
                null=True,
                verbose_name="場所",
            ),
        ),
        migrations.AlterField(
            model_name="presentation",
            name="authors",
            field=ckeditor.fields.RichTextField(
                blank=True,
                default="〇山田 太郎（〇〇大学）",
                help_text="例) 〇山田 太郎（〇〇大学），山田 二郎（〇〇大学），発表者の前に〇をつける(段落の書式は「標準」が推奨)",
                null=True,
                verbose_name="講演者と所属",
            ),
        ),
        migrations.AlterField(
            model_name="presentation",
            name="title",
            field=ckeditor.fields.RichTextField(
                blank=True,
                help_text="講演のタイトルを入力してください．(段落の書式は「標準」が推奨)",
                null=True,
                verbose_name="タイトル",
            ),
        ),
    ]
