# Generated by Django 4.1 on 2024-02-13 11:16

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ("meeting", "0022_alter_meeting_friendship_alter_meeting_style_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footer",
            name="body",
            field=django_ckeditor_5.fields.CKEditor5Field(
                help_text='本文を入力してください．(書式は"Paragraph")', verbose_name="本文"
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="friendship",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True,
                help_text='懇親会費を入力してください．(書式は"Paragraph")',
                null=True,
                verbose_name="懇親会費",
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="joint",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True,
                help_text='共催を入力してください.(書式は"Paragraph")',
                null=True,
                verbose_name="共催",
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="location",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True,
                help_text='開催する場所を入力してください．(書式は"Paragraph")',
                null=True,
                verbose_name="場所",
            ),
        ),
        migrations.AlterField(
            model_name="presentation",
            name="authors",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True,
                default="〇山田 太郎（〇〇大学）",
                help_text='例) 〇山田 太郎（〇〇大学），山田 二郎（〇〇大学），発表者の前に〇をつける(書式は"Paragraph")',
                null=True,
                verbose_name="講演者と所属",
            ),
        ),
        migrations.AlterField(
            model_name="presentation",
            name="title",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True,
                help_text="講演のタイトルを入力してください．(段落の書式は「標準」が推奨)",
                null=True,
                verbose_name="タイトル",
            ),
        ),
    ]
