# Generated by Django 4.2.2 on 2023-06-23 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SpModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="画像を選択してください．", upload_to="media", verbose_name="画像"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="画像の名前を入力してください．",
                        max_length=100,
                        verbose_name="画像の名前",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "特別賞の画像",
            },
        ),
        migrations.CreateModel(
            name="YearModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prizekey",
                    models.CharField(
                        help_text="賞のIDを入力してください．例：2021_鈴木・岡田記念賞",
                        max_length=100,
                        verbose_name="賞ID",
                    ),
                ),
                (
                    "AD",
                    models.IntegerField(
                        help_text="西暦で入力してください．例：2022", verbose_name="年度(西暦)"
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        help_text="和暦で入力してください．例：令和4",
                        max_length=10,
                        verbose_name="年度(和暦)",
                    ),
                ),
                (
                    "prize_type",
                    models.CharField(
                        choices=[
                            ("鈴木・岡田記念賞", "鈴木・岡田記念賞"),
                            ("鈴木・岡田賞", "鈴木・岡田賞"),
                            ("鈴木正根賞", "鈴木正根賞"),
                            ("特別賞", "特別賞"),
                            ("学生優秀発表賞", "学生優秀発表賞"),
                            ("学生シンポジウム優秀発表賞", "学生シンポジウム優秀発表賞"),
                            ("その他", "その他"),
                        ],
                        help_text="賞の種類を選択してください．",
                        max_length=100,
                        verbose_name="賞の種類",
                    ),
                ),
                (
                    "times",
                    models.IntegerField(
                        blank=True,
                        help_text="回数を入力してください．例：12  ※「鈴木・岡田記念賞」、「鈴木・岡田賞」、「鈴木正根賞」のみ入力",
                        null=True,
                        verbose_name="回数",
                    ),
                ),
                (
                    "chairman",
                    models.CharField(
                        blank=True,
                        help_text="選考委員長の名前を入力してください．例：山本 健司(徳島大学) ※「鈴木・岡田記念賞」、「鈴木・岡田賞」、「鈴木正根賞」のみ入力",
                        max_length=100,
                        null=True,
                        verbose_name="選考委員長",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "賞の年度テーブル",
            },
        ),
        migrations.CreateModel(
            name="SuzukiokadaModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("技術部門賞", "技術部門賞"),
                            ("技術部門奨励賞", "技術部門奨励賞"),
                            ("貢献賞", "貢献賞"),
                            ("特別賞", "特別賞"),
                            ("芸術部門賞", "芸術部門賞"),
                            ("芸術部門奨励賞", "芸術部門奨励賞"),
                            ("その他", "その他"),
                        ],
                        help_text="賞の名称を選択してください．",
                        max_length=20,
                        verbose_name="賞の名称",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="受賞者や受賞グループの名前を入力してください．例：吉川 宣一",
                        max_length=100,
                        verbose_name="受賞者・受賞グループ",
                    ),
                ),
                (
                    "affiliation",
                    models.CharField(
                        blank=True,
                        help_text="受賞者や受賞グループの所属を入力してください．例：埼玉大学",
                        max_length=100,
                        null=True,
                        verbose_name="所属",
                    ),
                ),
                (
                    "prizekey",
                    models.ForeignKey(
                        help_text="賞のIDを選択してください．",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prize",
                        to="prize.yearmodel",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "鈴木・岡田記念賞の受賞者テーブル",
            },
        ),
        migrations.CreateModel(
            name="ArticleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article_style",
                    models.CharField(
                        choices=[("PDF", "PDF"), ("html", "html"), ("その他", "その他")],
                        help_text="記事スタイルを選択してください．",
                        max_length=20,
                        verbose_name="記事スタイル",
                    ),
                ),
                (
                    "pdf",
                    models.CharField(
                        blank=True,
                        help_text="pdfのURLを入力してください． ※記事スタイルで「PDF」を選択した場合のみ",
                        max_length=1000,
                        null=True,
                        verbose_name="pdfのURL",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="タイトルや見出しを入力してください．例：技術部門賞(1件)",
                        max_length=1000,
                        verbose_name="タイトル・見出し",
                    ),
                ),
                (
                    "article",
                    models.TextField(
                        help_text="記事を入力してください．例：吉川氏は長年にわたり着実に・・・", verbose_name="記事"
                    ),
                ),
                (
                    "image_1",
                    models.ImageField(
                        blank=True,
                        help_text="画像を選択してください．(任意)",
                        null=True,
                        upload_to="media",
                        verbose_name="画像",
                    ),
                ),
                (
                    "image_2",
                    models.ImageField(
                        blank=True,
                        help_text="画像を選択してください．(任意)",
                        null=True,
                        upload_to="media",
                        verbose_name="画像",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        blank=True,
                        help_text="記事の順番を数字で入力してください．(任意)",
                        null=True,
                        verbose_name="順番",
                    ),
                ),
                (
                    "style",
                    models.IntegerField(
                        help_text="スタイルを数字で入力してください．", verbose_name="スタイル"
                    ),
                ),
                (
                    "prizekey",
                    models.ForeignKey(
                        default=1,
                        help_text="賞のIDを選択してください．",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="prize.yearmodel",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "記事テーブル",
            },
        ),
    ]
