# Generated by Django 4.2.2 on 2023-06-23 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("prize", "0002_alter_yearmodel_prizekey"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suzukiokadamodel",
            name="prizekey",
            field=models.ForeignKey(
                help_text="賞のIDを選択してください．",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prize",
                related_query_name="fprize",
                to="prize.yearmodel",
                verbose_name="賞ID",
            ),
        ),
    ]
