# Generated by Django 4.2.2 on 2023-07-31 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("prize", "0003_alter_suzukiokadamodel_prizekey"),
    ]

    operations = [
        migrations.CreateModel(
            name="Studentaward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="発表のタイトルを入力してください．",
                        max_length=100,
                        verbose_name="タイトル",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="氏名を入力してください．例：山田 太郎",
                        max_length=100,
                        verbose_name="氏名",
                    ),
                ),
                (
                    "prizekey",
                    models.ForeignKey(
                        help_text="賞のIDを選択してください．",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="studentawardprize",
                        related_query_name="studentawardfprize",
                        to="prize.yearmodel",
                        verbose_name="賞ID",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "学生賞の受賞者テーブル",
            },
        ),
    ]
