# Generated by Django 4.2 on 2023-09-14 08:43

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("prize", "0005_alter_articlemodel_prizekey_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articlemodel",
            name="image_1",
        ),
        migrations.RemoveField(
            model_name="articlemodel",
            name="image_2",
        ),
        migrations.RemoveField(
            model_name="articlemodel",
            name="order",
        ),
        migrations.RemoveField(
            model_name="articlemodel",
            name="style",
        ),
        migrations.AlterField(
            model_name="articlemodel",
            name="article",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                help_text="記事を入力してください．例：吉川氏は長年にわたり着実に・・・", verbose_name="記事"
            ),
        ),
    ]
