# Generated by Django 4.2 on 2023-09-15 05:28

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prize", "0006_remove_articlemodel_image_1_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="spmodel",
            options={
                "verbose_name": "spprize_name",
                "verbose_name_plural": "hodic_spprize",
            },
        ),
        migrations.RemoveField(
            model_name="spmodel",
            name="image",
        ),
        migrations.AddField(
            model_name="spmodel",
            name="affiliation",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="所属"
            ),
        ),
        migrations.AddField(
            model_name="spmodel",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="受傷日"),
        ),
        migrations.AddField(
            model_name="spmodel",
            name="text",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, help_text="画像を含めて作成してください。", null=True, verbose_name="記事"
            ),
        ),
        migrations.AlterField(
            model_name="articlemodel",
            name="pdf",
            field=models.FileField(
                blank=True,
                help_text="記事スタイルで「PDF」を選択した場合のみ",
                null=True,
                upload_to="",
                verbose_name="pdf",
            ),
        ),
        migrations.AlterField(
            model_name="spmodel",
            name="name",
            field=models.CharField(max_length=50, verbose_name="受賞者名"),
        ),
        migrations.AlterModelTable(
            name="spmodel",
            table="spprize_list",
        ),
    ]
