# Generated by Django 4.1 on 2023-09-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prize", "0007_alter_spmodel_options_remove_spmodel_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spmodel",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="受賞日"),
        ),
    ]
