# Generated by Django 4.1 on 2023-10-15 06:41

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prize", "0008_alter_spmodel_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlemodel",
            name="article",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True,
                help_text="記事を入力してください．例：吉川氏は長年にわたり着実に・・・",
                null=True,
                verbose_name="記事",
            ),
        ),
        migrations.AlterField(
            model_name="articlemodel",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="タイトルや見出しを入力してください．例：技術部門賞(1件)",
                max_length=1000,
                null=True,
                verbose_name="タイトル・見出し",
            ),
        ),
    ]
