# Generated by Django 4.1 on 2023-10-15 06:46

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("prize", "0009_alter_articlemodel_article_alter_articlemodel_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articlemodel",
            name="title",
        ),
        migrations.AlterField(
            model_name="articlemodel",
            name="article",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, help_text="記事を入力してください．", null=True, verbose_name="記事"
            ),
        ),
    ]
