# Generated by Django 4.1 on 2023-10-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prize", "0010_remove_articlemodel_title_alter_articlemodel_article"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="articlemodel",
            options={"verbose_name_plural": "鈴木・岡田記念賞の記事テーブル"},
        ),
        migrations.AlterField(
            model_name="articlemodel",
            name="pdf",
            field=models.FileField(
                blank=True,
                help_text="記事スタイルで「PDF」を選択した場合のみ",
                null=True,
                upload_to="suzukiokada/",
                verbose_name="pdf",
            ),
        ),
    ]
