# Generated by Django 4.2 on 2023-09-14 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="学会名（表示用）")),
                (
                    "name_ja",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="学会和名"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="学会英名"
                    ),
                ),
                (
                    "period_disp",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="開催時期（ソート用）"
                    ),
                ),
                (
                    "period",
                    models.DateField(
                        blank=True,
                        help_text="おおよその時期を入力",
                        null=True,
                        verbose_name="開催時期（ソート用）",
                    ),
                ),
                ("url", models.URLField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "conference_name",
                "verbose_name_plural": "conference",
                "db_table": "conference_list",
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opendate", models.DateField(verbose_name="開始日")),
                (
                    "closedate",
                    models.DateField(
                        help_text="1日開催の場合は開始日と同じにしてください。", verbose_name="終了日"
                    ),
                ),
                (
                    "deadline",
                    models.DateField(blank=True, null=True, verbose_name="投稿締切日"),
                ),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "name",
                    models.ForeignKey(
                        default="HODIC",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedule",
                        related_query_name="fschdule",
                        to="information.conference",
                        verbose_name="学会名",
                    ),
                ),
            ],
            options={
                "verbose_name": "schedule_name",
                "verbose_name_plural": "schedule",
                "db_table": "schedule_list",
            },
        ),
    ]
