# Generated by Django 4.2 on 2023-09-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conference",
            name="display",
            field=models.BooleanField(
                default=False, help_text="表示する場合True", verbose_name="表示・非表示"
            ),
        ),
        migrations.AlterField(
            model_name="conference",
            name="period_disp",
            field=models.CharField(
                blank=True, max_length=80, null=True, verbose_name="開催時期（表示用）"
            ),
        ),
    ]
