# Generated by Django 4.2 on 2023-09-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0002_conference_display_alter_conference_period_disp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conference",
            name="period",
            field=models.CharField(
                blank=True,
                help_text="おおよその時期を入力，例 3月中旬 → 0315",
                max_length=4,
                null=True,
                verbose_name="開催時期（ソート用）",
            ),
        ),
    ]
