# Generated by Django 4.2 on 2023-09-19 07:06

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0003_alter_conference_period"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="書籍名")),
                (
                    "pablisher",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="出版社"
                    ),
                ),
                (
                    "ISBN",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="ISBN"
                    ),
                ),
                (
                    "comment",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="書籍紹介"
                    ),
                ),
                ("thumbnail", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="基本的には出版元のURLを記載",
                        null=True,
                        verbose_name="書籍URL",
                    ),
                ),
            ],
            options={
                "verbose_name": "book_title",
                "verbose_name_plural": "book_content",
                "db_table": "book_list",
            },
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="タイトル")),
                ("order", models.IntegerField(verbose_name="ソート順")),
                ("introduction", models.TextField(verbose_name="紹介")),
                ("thumbnail", models.ImageField(blank=True, null=True, upload_to="")),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("society", "学会・協会・研究会"),
                            ("museum", "美術館・科学館・博物館"),
                            ("university", "大学関連"),
                            ("company", "企業"),
                            ("individual", "個人"),
                        ],
                        default="nihonuniv",
                        max_length=100,
                        verbose_name="カテゴリ",
                    ),
                ),
                ("logotype", models.BooleanField(default=True, verbose_name="横長true")),
            ],
            options={
                "verbose_name": "link_title",
                "verbose_name_plural": "link_content",
                "db_table": "link_list",
            },
        ),
        migrations.CreateModel(
            name="WebBookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="名前")),
                (
                    "comment",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="紹介文"
                    ),
                ),
                ("url", models.URLField(verbose_name="URL")),
            ],
            options={
                "verbose_name": "web_title",
                "verbose_name_plural": "web_content",
                "db_table": "web_list",
            },
        ),
        migrations.CreateModel(
            name="WordCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="カテゴリ名")),
            ],
            options={
                "verbose_name": "category_name",
                "verbose_name_plural": "wordcategory",
                "db_table": "category_list",
            },
        ),
        migrations.CreateModel(
            name="HoloWords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wordname", models.CharField(max_length=80, verbose_name="用語")),
                ("wordename", models.CharField(max_length=120, verbose_name="用語(英)")),
                ("abbreviation", models.CharField(max_length=50, verbose_name="略語")),
                (
                    "article",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True, verbose_name="解説記事"
                    ),
                ),
                ("display", models.BooleanField(default=False, verbose_name="掲載可否")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="holoword",
                        related_query_name="fholoword",
                        to="information.wordcategory",
                        verbose_name="カテゴリ",
                    ),
                ),
            ],
            options={
                "verbose_name": "word_name",
                "verbose_name_plural": "holowords",
                "db_table": "word_list",
            },
        ),
    ]
