# Generated by Django 4.1 on 2023-10-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0004_book_link_webbookmark_wordcategory_holowords"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="link/"),
        ),
    ]
