# Generated by Django 4.1 on 2023-10-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0005_alter_link_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holowords",
            name="abbreviation",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="略語"
            ),
        ),
        migrations.AlterField(
            model_name="holowords",
            name="wordename",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="用語(英)"
            ),
        ),
        migrations.AlterField(
            model_name="holowords",
            name="wordname",
            field=models.CharField(
                blank=True, max_length=80, null=True, verbose_name="用語"
            ),
        ),
    ]
