# Generated by Django 4.1 on 2024-02-13 11:16

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ("information", "0008_alter_book_comment_alter_webbookmark_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="comment",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name='書籍紹介(書式は"Paragraph")'
            ),
        ),
        migrations.AlterField(
            model_name="holowords",
            name="article",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name='解説記事(書式は"Paragraph")'
            ),
        ),
        migrations.AlterField(
            model_name="webbookmark",
            name="comment",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name='紹介文(書式は"Paragraph")'
            ),
        ),
    ]
