# Generated by Django 4.2.2 on 2023-06-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UpdateModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="更新日をカレンダーで選択してください．", verbose_name="更新日"
                    ),
                ),
                (
                    "content",
                    models.CharField(
                        help_text="更新内容を入力してください． 入力例：「更新情報 & News」を追加しました。",
                        max_length=100,
                        verbose_name="更新内容",
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        help_text="更新したページのリンクを入力してください． 入力例：http://127.0.0.1:8000/hodic/index.html",
                        max_length=500,
                        verbose_name="リンク",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("更新情報", "更新情報"), ("お知らせ", "お知らせ"), ("その他", "その他")],
                        help_text="カテゴリーを選択してください．",
                        max_length=100,
                        verbose_name="カテゴリー",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "「更新情報 & News」",
            },
        ),
    ]
