# Generated by Django 4.2.2 on 2023-07-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hodic", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ToppageImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="画像を選択してください．",
                        null=True,
                        upload_to="media",
                        verbose_name="画像",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="画像の名前を入力してください．例：画像1",
                        max_length=100,
                        verbose_name="画像の名前",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        help_text="画像の順番を数字で入力してください．", verbose_name="順番"
                    ),
                ),
                (
                    "alt",
                    models.CharField(
                        blank=True,
                        help_text="画像の説明を入力してください．(altタブのため任意)",
                        max_length=100,
                        null=True,
                        verbose_name="画像の説明",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "トップページの画像",
            },
        ),
    ]
