# Generated by Django 4.2.2 on 2023-07-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hodic", "0002_toppageimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="HodicImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="画像を選択してください．", upload_to="media", verbose_name="画像"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="画像の名前を入力してください．",
                        max_length=100,
                        verbose_name="画像の名前",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "HODICの画像",
            },
        ),
    ]
