# Generated by Django 4.2 on 2023-09-15 05:28

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hodic", "0003_hodicimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Circular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="例) 〇巻〇号（〇月発行），HODIC学生シンポジウム など",
                        max_length=80,
                        verbose_name="名前",
                    ),
                ),
                (
                    "number",
                    models.IntegerField(
                        blank=True,
                        default="1",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="巻数",
                    ),
                ),
                (
                    "volume",
                    models.IntegerField(
                        blank=True,
                        default="1",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                        verbose_name="号数",
                    ),
                ),
                ("date", models.DateField(verbose_name="発行日")),
                (
                    "pdf",
                    models.FileField(
                        upload_to="",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            )
                        ],
                        verbose_name="Circular",
                    ),
                ),
                (
                    "toc",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="目次"
                    ),
                ),
            ],
            options={
                "verbose_name": "circular_name",
                "verbose_name_plural": "circular",
                "db_table": "circular_list",
            },
        ),
        migrations.DeleteModel(
            name="HodicImage",
        ),
    ]
