# Generated by Django 4.2 on 2023-09-15 06:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hodic", "0004_circular_delete_hodicimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="circular",
            name="pdf",
            field=models.FileField(
                upload_to="circular/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
                verbose_name="Circular",
            ),
        ),
    ]
