# Generated by Django 4.2 on 2023-09-15 06:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hodic", "0005_alter_circular_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="circular",
            name="number",
            field=models.IntegerField(
                blank=True,
                default="1",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4),
                ],
                verbose_name="号数",
            ),
        ),
        migrations.AlterField(
            model_name="circular",
            name="volume",
            field=models.IntegerField(
                blank=True,
                default="1",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="巻数",
            ),
        ),
    ]
