# Generated by Django 4.1 on 2023-09-23 07:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hodic", "0006_alter_circular_number_alter_circular_volume"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ToppageImage",
        ),
    ]
