# Generated by Django 4.1 on 2023-10-03 02:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hodic", "0007_delete_toppageimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="circular",
            name="name",
            field=models.CharField(
                default="1巻1号（1月発行）",
                help_text="例) 〇巻〇号（〇月発行），HODIC学生シンポジウム など",
                max_length=80,
                verbose_name="名前",
            ),
        ),
    ]
