# Generated by Django 4.1 on 2023-10-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hodic", "0008_alter_circular_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="updatemodel",
            name="content",
            field=models.CharField(
                help_text="更新内容を入力してください．", max_length=100, verbose_name="更新内容"
            ),
        ),
        migrations.AlterField(
            model_name="updatemodel",
            name="link",
            field=models.CharField(
                help_text="更新したページのリンクを入力してください．", max_length=500, verbose_name="リンク"
            ),
        ),
    ]
