# Generated by Django 4.1 on 2023-11-19 07:14

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hodic", "0009_alter_updatemodel_content_alter_updatemodel_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="HodicCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="カテゴリ名")),
            ],
            options={
                "verbose_name": "hodiccategory_name",
                "verbose_name_plural": "hodiccategory",
                "db_table": "hodiccategory_list",
            },
        ),
        migrations.CreateModel(
            name="HodicArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        help_text="サブタイトルと入力してください",
                        max_length=100,
                        null=True,
                        verbose_name="サブタイトル",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default="1",
                        help_text="記事の順番を入力してください．",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="順番",
                    ),
                ),
                (
                    "article",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True,
                        help_text="記事を入力してください．",
                        null=True,
                        verbose_name="記事",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hodiccategory",
                        related_query_name="fhodiccategory",
                        to="hodic.hodiccategory",
                        verbose_name="カテゴリ",
                    ),
                ),
            ],
            options={
                "verbose_name": "hodicarticle_name",
                "verbose_name_plural": "hodicarticle",
                "db_table": "hodicarticle_list",
            },
        ),
    ]
