# Generated by Django 4.2.2 on 2024-01-11 02:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hodic", "0010_hodiccategory_hodicarticle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="circular",
            name="toc",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="目次(段落の書式は「標準」が推奨)"
            ),
        ),
    ]
