# Generated by Django 4.2.2 on 2024-02-05 04:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hodic", "0011_alter_circular_toc"),
    ]

    operations = [
        migrations.CreateModel(
            name="Manual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名前")),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="カテゴリー"
                    ),
                ),
                (
                    "pdf",
                    models.FileField(
                        upload_to="manual/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            )
                        ],
                        verbose_name="マニュアル",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="hodicarticle",
            name="subtitle",
            field=models.CharField(
                blank=True,
                help_text="サブタイトルを入力してください",
                max_length=100,
                null=True,
                verbose_name="サブタイトル",
            ),
        ),
    ]
