# Generated by Django 4.1 on 2024-02-11 08:06

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ("hodic", "0012_manual_alter_hodicarticle_subtitle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="circular",
            name="toc",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="目次(段落の書式は「標準」が推奨)"
            ),
        ),
    ]
