# Generated by Django 4.1 on 2024-02-13 11:16

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ("hodic", "0013_alter_circular_toc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="circular",
            name="toc",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name='目次(書式は"Paragraph")'
            ),
        ),
        migrations.AlterField(
            model_name="hodicarticle",
            name="article",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True,
                help_text='記事を入力してください．(書式は"Paragraph")',
                null=True,
                verbose_name="記事",
            ),
        ),
    ]
